# Generated by Django 3.2.3 on 2021-05-24 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_lugar_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
