# Generated by Django 3.2.3 on 2021-05-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210524_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='destino',
            field=models.BooleanField(default=False),
        ),
    ]
